# Generated by Django 4.0.6 on 2022-07-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='date_of_birth',
            field=models.DateField(auto_now=True),
        ),
    ]
