# Generated by Django 4.0.6 on 2022-07-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfolio_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='percent',
            new_name='percentage',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='date_of_birth',
            field=models.DateField(blank=True),
        ),
    ]
