# Generated by Django 4.0.6 on 2022-07-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='services',
            field=models.ManyToManyField(blank=True, to='portfolio.service'),
        ),
    ]
