# Generated by Django 4.0.6 on 2022-07-07 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_portfolio_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='work',
            new_name='works',
        ),
    ]
