# Generated by Django 4.0.6 on 2022-07-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='portfolio.contact'),
        ),
    ]
