# Generated by Django 4.0.6 on 2022-07-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_contact_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='google_map',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
