# Generated by Django 4.0.6 on 2022-07-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_portfolio_google_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='footer_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='google_map',
            field=models.CharField(blank=True, max_length=555),
        ),
    ]
